$(document).ready(function(){
    $(".design").click(function(){
        $("#design").show();
        $(".design").hide();
    })
    $("#design").click(function(){
        $(".design").show();
        $("#design").hide();
    })
    $(".development").click(function(){
        $("#development").show();
        $(".development").hide();
    })
    $("#development").click(function(){
        $(".development").show();
        $("#development").hide();
    })
    $("#product").click(function(){
        $(".product").show();
        $("#product").hide();
    })
    $(".product").click(function(){
        $(".product").hide();
        $("#product").show();
    })
});
